import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'webshopx',
      link: {
        type: 'generated-index',
        title: 'webshopx',
        description: 'WebShopX 文档导航',
      },
      items: [
        {
          type: 'category',
          label: '玩家文档',
          link: {
            type: 'generated-index',
            title: '玩家文档',
            description: '面向普通玩家的使用说明与排障。',
          },
          items: [{type: 'autogenerated', dirName: 'webshopx/player'}],
        },
        {
          type: 'category',
          label: '服主文档',
          link: {
            type: 'generated-index',
            title: '服主文档',
            description: '面向服主/管理员的部署、配置与运营文档。',
          },
          items: [{type: 'autogenerated', dirName: 'webshopx/admin'}],
        },
      ],
    },
  ],
};

export default sidebars;
